const signatures = require('sodium-signatures')
const encryption = require('sodium-encryption')
const ed2curve = require('ed2curve')

// service and user are ed25519 key pair generated by signatures.keyPair()

function msg (sender, receiver, payload) {
  var sig = signatures.sign(Buffer(payload), sender.secretKey)
  var nonce = encryption.nonce()

  var sharedKey = encryption.scalarMultiplication(ed2curve.convertSecretKey(sender.secretKey), ed2curve.convertPublicKey(receiver.publicKey))

  return {
    nonce,
    payload: encryption.encrypt(Buffer(signed(sig, payload)), nonce, sharedKey)
  }
}

function openMsg (sender, receiver, msg) {
  var sharedKey = encryption.scalarMultiplication(ed2curve.convertSecretKey(receiver.secretKey), ed2curve.convertPublicKey(sender.publicKey))
  var decrypted = encryption.decrypt(msg.payload, msg.nonce, sharedKey)
  if (!decrypted) return null

  decrypted = JSON.parse(decrypted)

  if (!signatures.verify(Buffer(decrypted.payload), Buffer.from(decrypted.sig, 'hex'), sender.publicKey)) return null

  return decrypted.payload
}

module.exports = {msg, openMsg}

function signed (sig, payload) {
  return JSON.stringify({sig: sig.toString('hex'), payload: payload.toString()})
}
